language: python

# Use container based infrastructure
sudo: false

env:
  - TOX_ENV=pep8
  - TOX_ENV=py27-dj11-cms34
  - TOX_ENV=py27-dj10-cms34
  - TOX_ENV=py27-dj19-cms33
  - TOX_ENV=py27-dj18-cms32

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
